---
title: "M4 Graphic"
author: "David Moberg"
date: "10/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, messages = FALSE, warning = FALSE)
library(tidyverse)
library(janitor)
library(readxl)
library(gt)
library(plotly)
library(reprex)
```

```{r Read in and clean the data I need, include=FALSE}
m4Data <- read_xlsx(path = "raw-data/august2019/Table_1_11_B.xlsx", skip = 5)
m4Data<-m4Data%>%head(-2)%>%clean_names()%>%select("census_division_and_state", "june_2019_ytd_2", "june_2018_ytd_3", "percentage_change")

```

```{r Create graph}
plotData<-subset(m4Data, census_division_and_state %in% c("New England", "Middle Atlantic", "East North Central", "West North Central", "South Atlantic", "East South Central", "West South Central", "Mountain", "Pacific Contiguous", "Pacific Noncontiguous"))%>%gt()


plotData<- plotData%>%mutate(yearDiff = june_2019_ytd_2-june_2018_ytd_3)

energyPlot <- ggplot(plotData, aes(x=census_division_and_state, y=yearDiff, color = census_division_and_state, fill = census_division_and_state)) + geom_col()+theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank())+labs(title = "Change in Electrical Consumption from 2018 to 2019", subtitle = "Measured by region of the US", y="Thousand Megawatt-Hours", fill = "Region of the US") + guides(color = FALSE)

suppressWarnings(energyPlot)
```


